### ISSUE TITLE
Error when running NanSurfaceSolver

### ISSUE THREAD

**Issue by Gabrielsvc** [dongqi-DQ/WRF4PALM#11]
> multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/isi-user/miniconda3/envs/wrf4palm/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/isi-user/Repos/WRF4PALM/dynamic_util/surface_nan_solver.py", line 57, in solve_surface
    ds_we[var].loc[dict(time=ts)][:,j,bc] = surface_nan_uv(ds_we[var].sel(time=ts)[:,j,bc].data,z,surface_value)
  File "/home/isi-user/Repos/WRF4PALM/dynamic_util/surface_nan_solver.py", line 21, in surface_nan_uv
    a = (data[nan_idx]-uv10)/np.log(z[nan_idx]-10)
IndexError: index 120 is out of bounds for axis 0 with size 120

I think this could be solved by changing the calculation of the nan_idx variable. Why is it being increased by 1 in all functions (right [here](https://github.com/dongqi-DQ/WRF4PALM/blob/v1.1/dynamic_util/surface_nan_solver.py#L18) for example)?

`nan_idx = int(nan_idx[-1])+1` would become `nan_idx = int(nan_idx[-1])`

Our namelist is attached to the issue.
[namelist_wrf4palm.txt](https://github.com/dongqi-DQ/WRF4PALM/files/8412583/namelist_wrf4palm.txt)
And here is the wrfout file, which contains the first day of january with 48 timesteps, one for each 30 minutes.
[Drive link for wrfout file](https://drive.google.com/file/d/1rvUFTABNIH1g6GsuUo-vr0WGkJJaImxe/view?usp=sharing)

**Comment by dongqi-DQ** [comment]
I used ```+1``` because the nan_idx[-1] returns the highest vertical level with NaN and the NaN solver uses the nearest valid value at the vertical column to fill the NaNs. 

I've got a few users reported this issue. It seems that wrf4palm works fine when the grid spacing is greater than 10 m. And if this nan solver error occurs, it's because the topography height from WRF is higher than the configured PALM domain height. But this error could keep popping up when grid spacing is at say 4 m, and changing the index line in nan solver cannot address the problem. This is due to a bug in the interpolation code I think and it was identified in Issue #7.

**Comment by xanfus** [comment]
Hello from issue #7 . I've figured out, my v1.1.1 wasn't framing PALM domain from outwards. Consider x axis of PALM domain is 1.2 WRF.dx. Algorithm then picks up only nodes i and i+1 instead of i and i+2. Interpolation isn't performed in parts of PALM domain over remaining 0.2 of WRF.dx, extrapolation either, NaN values are resident there. Then NanSurfaceSolver has no non-NaN value to extrapolate down to PALM domain's ground level in these "fog of war" areas. Fixed.

I have to update my fork. I'll omit testing against _quick_compare.py_. It's just hard to obtain understanding, how it's different from _run_config_wrf4palm.py_  without refactoring into common execution sequences.

**Comment by xanfus** [comment]
https://github.com/xanfus/WRF4PALM/tree/v1.1.2-beta0
As i remember, a corner of PALM domain snapped to WRF domain grid point in v1.1.1, which had been fixed in v1.1.2-beta0. Could be an overprecision.

**Comment by Gabrielsvc** [comment]
Hi everyone, sorry for the long absence, I was recovering from a surgery. I've tried with the code from @xanfus repository and got the same error when trying to run it, also tested different grid spacing(10m, 50m and 100m) and got the same results(error on the NaN solver)

> I used +1 because the nan_idx[-1] returns the highest vertical level with NaN and the NaN solver uses the nearest valid value at the vertical column to fill the NaNs.

I see, then my change doesn't help at all, I'm just leaving the value of NaN at all points where NaN was already a value. I will read a bit further into issue #7 . Thanks for the feedback!

**Comment by dongqi-DQ** [comment]
I might have found why the surface nan solver doesn't work. The coordinates were not passed to the interpolated dataset properly. I looked into the code and made the fix [here](https://github.com/dongqi-DQ/WRF4PALM/commit/79f32b7dbca3a21ba60f7312156b49ad8ca535e2) . 

Hope that fix the issue.

**Comment by Gabrielsvc** [comment]
Will try it out and report back, thanks a lot!

**Comment by Gabrielsvc** [comment]
I've retried with the changes above for the same example and still got some NaNs on my domain(white space), using the same configuration and files provided, here's a look at the result:
![image](https://user-images.githubusercontent.com/7093444/165161951-692c9787-8cdb-443d-bbc4-37f789d61b64.png)

**Comment by dongqi-DQ** [comment]
@Gabrielsvc, I tried the same wrfout and namelist you provided, and I cannot replicate the issue. The code executed successfully without any error, and there is no NaNs in the dynamic driver. 

![image](https://user-images.githubusercontent.com/22810987/165184051-cc0b283b-f534-4f1d-864a-65a543d29c1c.png)

In addition to my latest change on the coordinates, I merged the latest pull from @xanfus. Can you check that all other utility is up-to-date? Thanks.

**Comment by xanfus** [comment]
@Gabrielsvc, what commit were you on? 832e302?

**Comment by Gabrielsvc** [comment]
Hi everyone, sorry for the long await time, I've not been notified on the comments for some reason. At the time I was using the latest commit, so I would say [422f938](https://github.com/dongqi-DQ/WRF4PALM/commit/422f93849fc34cc9c53f86e87015dd289a34c2e4). Since then I haven't been able to test wrf4palm. I'm getting back to it now.

**Comment by Gabrielsvc** [comment]
Will notify if the error still persists when I run an example

**Comment by Gabrielsvc** [comment]
Can confirm still getting same output with current branch [c336f59](https://github.com/dongqi-DQ/WRF4PALM/commit/c336f5970a50357d51a4efb9bc9df676a89719ee):

> Traceback (most recent call last):
> 
>   File "/home/gsvc/.local/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/gsvc/Repos/WRF4PALM/dynamic_util/surface_nan_solver.py", line 55, in solve_surface
>     ds_we[var].loc[dict(time=ts)][:,j,bc] = surface_nan_uv(ds_we[var].sel(time=ts)[:,j,bc].data,z,surface_value)
>   File "/home/gsvc/Repos/WRF4PALM/dynamic_util/surface_nan_solver.py", line 19, in surface_nan_uv
>     a = (data[nan_idx]-uv10)/np.log(z[nan_idx]-10)
> IndexError: index 120 is out of bounds for axis 0 with size 120

Re-reading previous comments I might have found the source of the error:
> I used +1 because the nan_idx[-1] returns the highest vertical level with NaN and the NaN solver uses the nearest valid value at the vertical column to fill the NaNs.

Printing the `nan_idx` there are cases where the whole column has NaN values. In this case, the code iterates through the whole array and doesn't find a valid value, then it tries to grab the next index, which is a invalid position. Still, it's weird that we have whole columns without any valid value
shape of data: (120,)             
nan_idx: [[  0]                                                                                
 [  1]                  
 .....
 [ 119]]
Here are the namelist and a link for the wrfout that I'm using:

[wrfout file](https://senairn-my.sharepoint.com/:u:/g/personal/gabrielconta_isi-er_com_br/EYgxxzDLgxNFtBehnJ2BgKEBT2tW1_KyQMlmtRbdhV2gHg?e=4kp8Dn)

[namelist.wrf4palm.txt](https://github.com/dongqi-DQ/WRF4PALM/files/9424941/namelist.wrf4palm.txt)

**Comment by Gabrielsvc** [comment]
Ah-ha, found my problem. I was using the wrong projection in the field `palm_proj` (`EPSG:2193` instead of `EPSG:5641`) I Think i can now close the issue, since the problem was on my end. A nice addition would be a verification for whole columns of NaN in the nan_solver. Cheers guys
